server:
  port: 8083
spring:
  application:
    name: Api-Gateway

  zipkin:
      base-url: http://localhost:50154
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**



